// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3E6gyhHiFe-kl2kYGuv3elYOq7chcs00',
    appId: '1:782447481056:android:971b783380ca493a424085',
    messagingSenderId: '782447481056',
    projectId: 'genfit-94db6',
    storageBucket: 'genfit-94db6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfdiYOrS9Q_gQRA8PJJjx_vaFVRCVN840',
    appId: '1:782447481056:ios:68d5db2ed2b58a76424085',
    messagingSenderId: '782447481056',
    projectId: 'genfit-94db6',
    storageBucket: 'genfit-94db6.firebasestorage.app',
    iosBundleId: 'com.example.genFit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4X7jjR7L2kapmNcmFFI2p5zxCtYvga2c',
    appId: '1:782447481056:web:24859df9acea45ff424085',
    messagingSenderId: '782447481056',
    projectId: 'genfit-94db6',
    authDomain: 'genfit-94db6.firebaseapp.com',
    storageBucket: 'genfit-94db6.firebasestorage.app',
  );
}
